//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExtentBazaEntities : DbContext
    {
        public ExtentBazaEntities()
            : base("name=ExtentBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivnost> Aktivnost { get; set; }
        public virtual DbSet<Dokumentacija> Dokumentacija { get; set; }
        public virtual DbSet<GeneralniTrosak> GeneralniTrosak { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<PDF> PDF { get; set; }
        public virtual DbSet<Projekat> Projekat { get; set; }
        public virtual DbSet<Trosak> Trosak { get; set; }
        public virtual DbSet<Zahtev> Zahtev { get; set; }
    }
}
