//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trosak
    {
        public int IDProjekta { get; set; }
        public string Kategorija { get; set; }
        public string Podkategorija { get; set; }
        public string Artikal { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<int> Cena { get; set; }
        public int IDTroska { get; set; }
        public string Datum { get; set; }
        public Nullable<bool> Stanje { get; set; }

        public int UkupnaCena { get => (int)Kolicina * (int)Cena; }

        public override string ToString()
        {
            return $"{Kategorija}/{Podkategorija}  Naziv artikla: {Artikal}  Kolicina: {Kolicina}  Cena: {Cena}";
        }

        public virtual GeneralniTrosak GeneralniTrosak { get; set; }
    }
}
