//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahtev
    {
        public int IDZahteva { get; set; }
        public int IDProjekta { get; set; }
        public string KorisnickoImePosiljaoca { get; set; }
        public string KorisnickoImePrimaoca { get; set; }
        public string Naslov { get; set; }
        public string Poruka { get; set; }
        public Nullable<bool> Odgovor { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Projekat Projekat { get; set; }
    }
}
